# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='rpapp/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
