# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpapp', '0002_auto_20180713_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arendator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_time', models.IntegerField(max_length=30)),
                ('price', models.IntegerField(max_length=30)),
                ('rental_condition', models.CharField(choices=[(None, 'unknown'), ('fr', 'free'), ('ld', 'leased')], default='fr', max_length=2)),
                ('arendator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpapp.Arendator')),
            ],
        ),
    ]
