# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpapp', '0003_arendator_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contract',
            new_name='contract_file',
        ),
        migrations.AddField(
            model_name='contract',
            name='rent_obj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rpapp.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rent_time',
            field=models.IntegerField(),
        ),
    ]
