# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpapp', '0004_auto_20180714_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
