# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-15 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpapp', '0008_auto_20180714_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_by_contract',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rent_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
